import { useState } from "react";
import CodeMirror from "@uiw/react-codemirror";
import { css } from "@codemirror/lang-css";
import { html } from "@codemirror/lang-html";
import { Copy, Eye, Plus, Save, Trash2 } from "lucide-react";
import type { PdfTemplate } from "@shared/reportTypes";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import {
  useCreatePdfTemplate,
  useDeletePdfTemplate,
  useDuplicatePdfTemplate,
  usePdfTemplates,
  usePreviewPdfTemplate,
  useUpdatePdfTemplate,
} from "@/hooks/use-entities";

const DEFAULT_PDF_TEMPLATE = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>{{page.css}}</style>
</head>
<body>
  <section class="cover">
    <div class="cover__brand">
      <div class="cover__mark">F</div>
      <div>
        <div class="cover__product">Forenotes</div>
        <div class="cover__tagline">Digital Forensics & Incident Response</div>
      </div>
    </div>
    <div class="cover__report-type">{{report.type}}</div>
    <div class="cover__eyebrow">Confidential DFIR Report</div>
    <h1 class="cover__title">{{report.title}}</h1>
    <p class="cover__subtitle">{{incident.name}}</p>
    <div class="cover__meta-grid">
      <div class="cover__meta-card">
        <span class="cover__meta-label">Client</span>
        <div class="cover__meta-value">{{incident.clientName}}</div>
      </div>
      <div class="cover__meta-card">
        <span class="cover__meta-label">Status</span>
        <div class="cover__meta-value">{{incident.status}}</div>
      </div>
      <div class="cover__meta-card">
        <span class="cover__meta-label">Incident</span>
        <div class="cover__meta-value">{{incident.name}}</div>
      </div>
      <div class="cover__meta-card">
        <span class="cover__meta-label">Generated</span>
        <div class="cover__meta-value">{{report.generatedAt}}</div>
      </div>
      <div class="cover__meta-card cover__meta-card--full">
        <span class="cover__meta-label">Template Engine</span>
        <div class="cover__meta-value">Markdown content rendered into a branded HTML document</div>
      </div>
    </div>
  </section>
  <section class="document-shell">
    <div class="document-shell__header">
      <div class="document-shell__kicker">Forenotes incident report</div>
      <h2 class="document-shell__title">{{report.title}}</h2>
      <p class="document-shell__lede">Markdown sections, tables, lists, and callouts inherit presentation from this PDF template.</p>
      <div class="document-shell__meta">
        <div class="document-shell__meta-item">
          <span>Incident</span>
          <strong>{{incident.name}}</strong>
        </div>
        <div class="document-shell__meta-item">
          <span>Client</span>
          <strong>{{incident.clientName}}</strong>
        </div>
        <div class="document-shell__meta-item">
          <span>Generated</span>
          <strong>{{report.generatedAt}}</strong>
        </div>
      </div>
    </div>
    <main class="document-shell__content">
      {{content}}
    </main>
  </section>
  <section class="document-footer">
    <span>Generated by Forenotes</span>
    <span>{{report.type}}</span>
  </section>
</body>
</html>`;

const DEFAULT_PDF_CSS = `@page {
  size: A4;
  margin: 18mm 18mm 20mm 26mm;
}

html {
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

body {
  font-family: Inter, Arial, sans-serif;
  color: #17201d;
  font-size: 12px;
  line-height: 1.6;
  margin: 0;
  position: relative;
}
body::before {
  background: #127c73;
  bottom: 0;
  content: "";
  left: 0;
  position: fixed;
  top: 0;
  width: 14mm;
}
.cover {
  min-height: calc(297mm - 38mm);
  page-break-after: always;
  padding: 34mm 0 12mm 34mm;
  position: relative;
}
.cover::before {
  background: linear-gradient(135deg, rgba(255, 255, 255, 0) 41%, rgba(214, 238, 234, 0.92) 41%);
  content: "";
  inset: 0 -18mm 0 11mm;
  position: absolute;
  z-index: -2;
}
.cover::after {
  background: radial-gradient(circle at center, rgba(193, 227, 221, 0.45) 0%, rgba(193, 227, 221, 0.45) 62%, rgba(193, 227, 221, 0) 62%);
  border-radius: 50%;
  bottom: -20mm;
  content: "";
  height: 160mm;
  position: absolute;
  right: -34mm;
  width: 160mm;
  z-index: -1;
}
.cover__brand {
  align-items: center;
  display: flex;
  gap: 14px;
  margin-bottom: 18px;
}
.cover__mark {
  align-items: center;
  background: #127c73;
  border-radius: 16px;
  color: #ffffff;
  display: inline-flex;
  font-size: 28px;
  font-weight: 800;
  height: 56px;
  justify-content: center;
  width: 56px;
}
.cover__product {
  font-size: 28px;
  font-weight: 800;
  line-height: 1.1;
}
.cover__tagline {
  color: #6a7773;
  font-size: 11px;
  letter-spacing: 0.16em;
  margin-top: 4px;
  text-transform: uppercase;
}
.cover__report-type {
  border: 1px solid #d7e2de;
  border-radius: 999px;
  color: #135f59;
  font-size: 12px;
  font-weight: 700;
  margin: 8px 0 160px;
  max-width: 440px;
  padding: 8px 18px;
  text-transform: uppercase;
}
.cover__eyebrow {
  color: #0f766e;
  font-size: 11px;
  letter-spacing: 0.08em;
  font-weight: 700;
  margin-bottom: 14px;
  text-transform: uppercase;
}
.cover__title {
  font-size: 44px;
  font-weight: 800;
  letter-spacing: 0;
  line-height: 1.05;
  margin: 0;
  max-width: 520px;
}
.cover__subtitle {
  color: #6a7773;
  font-size: 16px;
  margin: 18px 0 88px;
  max-width: 460px;
}
.cover__meta-grid {
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  max-width: 520px;
}
.cover__meta-card {
  background: rgba(255, 255, 255, 0.86);
  border: 1px solid #d7e2de;
  border-radius: 16px;
  padding: 14px 18px;
}
.cover__meta-card--full {
  grid-column: 1 / -1;
}
.cover__meta-label {
  color: #6a7773;
  display: block;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.08em;
  margin-bottom: 8px;
  text-transform: uppercase;
}
.cover__meta-value {
  font-size: 17px;
  font-weight: 700;
  line-height: 1.3;
}
.document-shell {
  padding-left: 34mm;
}
.document-shell__header {
  border-bottom: 1px solid #d7e2de;
  margin-bottom: 18px;
  padding-bottom: 16px;
}
.document-shell__kicker {
  color: #0f766e;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  margin-bottom: 8px;
  text-transform: uppercase;
}
.document-shell__title {
  font-size: 28px;
  font-weight: 800;
  line-height: 1.15;
  margin: 0;
}
.document-shell__lede {
  color: #52605d;
  font-size: 13px;
  margin: 10px 0 0;
}
.document-shell__meta {
  display: grid;
  gap: 10px;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  margin-top: 16px;
}
.document-shell__meta-item {
  background: #f5f9f8;
  border: 1px solid #dfe8e5;
  border-radius: 12px;
  padding: 10px 12px;
}
.document-shell__meta-item span {
  color: #65726e;
  display: block;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.08em;
  margin-bottom: 6px;
  text-transform: uppercase;
}
.document-shell__meta-item strong {
  display: block;
  font-size: 12px;
  line-height: 1.4;
}
.document-shell__content {
  min-width: 0;
}
.forenotes-markdown > :first-child {
  margin-top: 0;
}
.forenotes-markdown > :last-child {
  margin-bottom: 0;
}
.forenotes-markdown h1,
.forenotes-markdown h2,
.forenotes-markdown h3,
.forenotes-markdown h4,
.forenotes-markdown h5,
.forenotes-markdown h6 {
  color: #16211f;
  font-weight: 800;
  letter-spacing: 0;
  line-height: 1.2;
  margin: 24px 0 10px;
  page-break-after: avoid;
}
.forenotes-markdown h1 {
  border-bottom: 1px solid #d7e2de;
  font-size: 26px;
  margin-top: 0;
  padding-bottom: 10px;
}
.forenotes-markdown h2 {
  border-bottom: 1px solid #e3ebe8;
  font-size: 20px;
  padding-bottom: 6px;
}
.forenotes-markdown h3 {
  font-size: 16px;
}
.forenotes-markdown p,
.forenotes-markdown ul,
.forenotes-markdown ol,
.forenotes-markdown blockquote,
.forenotes-markdown pre,
.forenotes-markdown table {
  margin: 12px 0 16px;
}
.forenotes-markdown p {
  color: #24312e;
}
.forenotes-markdown ul,
.forenotes-markdown ol {
  padding-left: 20px;
}
.forenotes-markdown li + li {
  margin-top: 6px;
}
.forenotes-markdown blockquote {
  background: #f4faf8;
  border-left: 4px solid #0f766e;
  border-radius: 0 12px 12px 0;
  color: #41514d;
  padding: 12px 14px;
}
.forenotes-markdown hr {
  border: 0;
  border-top: 1px solid #d7e2de;
  margin: 20px 0;
}
.forenotes-markdown table {
  background: #ffffff;
  border: 1px solid #d7e2de;
  border-radius: 12px;
  border-collapse: separate;
  border-spacing: 0;
  font-size: 11px;
  overflow: hidden;
  page-break-inside: auto;
  table-layout: fixed;
  width: 100%;
}
.forenotes-markdown thead {
  display: table-header-group;
}
.forenotes-markdown tr {
  page-break-inside: avoid;
  page-break-after: auto;
}
.forenotes-markdown tbody tr:nth-child(even) {
  background: #f8fbfa;
}
.forenotes-markdown th,
.forenotes-markdown td {
  border-bottom: 1px solid #dfe8e5;
  border-right: 1px solid #dfe8e5;
  padding: 8px 10px;
  vertical-align: top;
  overflow-wrap: anywhere;
}
.forenotes-markdown tr > *:last-child {
  border-right: 0;
}
.forenotes-markdown tbody tr:last-child > * {
  border-bottom: 0;
}
.forenotes-markdown th {
  background: #eef5f3;
  color: #163430;
  font-weight: 700;
  text-align: left;
}
.forenotes-markdown code {
  font-family: Consolas, monospace;
  background: #f1f3f2;
  border-radius: 3px;
  padding: 1px 4px;
}
.forenotes-markdown pre {
  background: #f1f3f2;
  border-radius: 10px;
  overflow-wrap: break-word;
  padding: 12px 14px;
  white-space: pre-wrap;
}
.forenotes-markdown pre code {
  background: transparent;
  padding: 0;
}
.forenotes-markdown a {
  color: #0f766e;
}
.document-footer {
  border-top: 1px solid #d7e2de;
  color: #66716d;
  display: flex;
  font-size: 10px;
  justify-content: space-between;
  margin-top: 24px;
  padding: 12px 0 0 34mm;
}
@media print {
  .cover {
    min-height: calc(297mm - 38mm);
  }
}`;

type PdfWorkspaceTab = "details" | "html" | "css" | "preview";

function messageFromError(error: unknown, fallback: string) {
  return error instanceof Error ? error.message : fallback;
}

function newPdfTemplateDraft(): PdfTemplate {
  return {
    id: "",
    name: "Forenotes Teal",
    description: "",
    scope: "global",
    incidentId: null,
    htmlTemplate: DEFAULT_PDF_TEMPLATE,
    css: DEFAULT_PDF_CSS,
    isDefault: false,
    createdBy: "",
    createdAt: "",
    updatedAt: "",
  };
}

function CodeEditorField({
  label,
  value,
  onChange,
  height,
  language,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  height: string;
  language: "html" | "css";
}) {
  return (
    <label className="space-y-1 text-sm font-medium">
      {label}
      <div className="cm-editor-wrapper">
        <CodeMirror
          value={value}
          onChange={onChange}
          extensions={[language === "html" ? html() : css()]}
          height={height}
          basicSetup={{
            lineNumbers: true,
            foldGutter: true,
            highlightActiveLine: true,
            bracketMatching: true,
          }}
        />
      </div>
    </label>
  );
}

export function PdfTemplateWorkspace() {
  const pdfTemplatesQuery = usePdfTemplates();
  const createPdfTemplate = useCreatePdfTemplate();
  const updatePdfTemplate = useUpdatePdfTemplate();
  const duplicatePdfTemplate = useDuplicatePdfTemplate();
  const deletePdfTemplate = useDeletePdfTemplate();
  const previewPdfTemplate = usePreviewPdfTemplate();
  const [pdfDraft, setPdfDraft] = useState<PdfTemplate | null>(null);
  const [pdfWorkspaceTab, setPdfWorkspaceTab] = useState<PdfWorkspaceTab>("details");
  const [pdfMessage, setPdfMessage] = useState<string | null>(null);
  const pdfTemplates = pdfTemplatesQuery.data?.templates ?? [];

  function savePdfTemplate() {
    if (!pdfDraft) return;
    setPdfMessage(null);
    const payload = {
      name: pdfDraft.name,
      description: pdfDraft.description ?? "",
      scope: pdfDraft.scope,
      incidentId: pdfDraft.incidentId ?? null,
      htmlTemplate: pdfDraft.htmlTemplate,
      css: pdfDraft.css,
      isDefault: pdfDraft.isDefault,
    };
    if (pdfDraft.id) {
      updatePdfTemplate.mutate(
        { templateId: pdfDraft.id, data: payload },
        {
          onSuccess: (result) => {
            setPdfDraft(result.template);
            setPdfMessage("PDF template saved.");
          },
          onError: (error) => setPdfMessage(messageFromError(error, "Unable to save PDF template.")),
        }
      );
      return;
    }
    createPdfTemplate.mutate(payload, {
      onSuccess: (result) => {
        setPdfDraft(result.template);
        setPdfMessage("PDF template created.");
      },
      onError: (error) => setPdfMessage(messageFromError(error, "Unable to create PDF template.")),
    });
  }

  function previewCurrentPdfTemplate() {
    if (!pdfDraft) return;
    setPdfMessage(null);
    previewPdfTemplate.mutate(
      {
        pdfTemplateId: pdfDraft.id || undefined,
        htmlTemplate: pdfDraft.htmlTemplate,
        css: pdfDraft.css,
      },
      {
        onSuccess: () => setPdfMessage("Preview rendered below. Unsafe scripts and handlers are stripped server-side."),
        onError: (error) => setPdfMessage(messageFromError(error, "Unable to preview PDF template.")),
      }
    );
  }

  return (
    <div className="space-y-4" data-report-editor="pdf-template">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold">PDF Templates</h3>
          <p className="text-xs text-[var(--color-text-muted)]">HTML/CSS wrappers for Markdown report exports.</p>
        </div>
        <Button
          type="button"
          variant="outline"
          onClick={() => {
            setPdfDraft(newPdfTemplateDraft());
            setPdfWorkspaceTab("details");
          }}
        >
          <Plus className="h-4 w-4" />
          Create template
        </Button>
      </div>

      <div className="grid gap-4 lg:grid-cols-[minmax(240px,320px)_minmax(0,1fr)]">
        <div className="space-y-2">
          {pdfTemplates.length === 0 ? (
            <div className="rounded border border-dashed border-[var(--color-border)] p-4 text-sm text-[var(--color-text-muted)]">
              No custom PDF templates yet. Exports use the built-in default.
            </div>
          ) : (
            pdfTemplates.map((template) => (
              <article key={template.id} className="rounded border border-[var(--color-border)] bg-[var(--color-background)] p-3">
                <button
                  type="button"
                  className="w-full text-left"
                  onClick={() => {
                    setPdfDraft(template);
                    setPdfWorkspaceTab("details");
                  }}
                >
                  <span className="block truncate text-sm font-medium">{template.name}</span>
                  <span className="block text-xs text-[var(--color-text-muted)]">
                    {template.scope}
                    {template.isDefault ? " / default" : ""}
                  </span>
                </button>
                <div className="mt-3 flex gap-1">
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    title="Duplicate template"
                    onClick={() => duplicatePdfTemplate.mutate({ templateId: template.id })}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    title="Delete template"
                    onClick={() => deletePdfTemplate.mutate(template.id)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </article>
            ))
          )}
        </div>

        <div className="min-w-0">
          {pdfDraft ? (
            <div className="space-y-3">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h4 className="text-sm font-semibold">{pdfDraft.name || "Untitled PDF template"}</h4>
                  <p className="text-xs text-[var(--color-text-muted)]">Edit metadata, HTML, CSS, and preview output in separate workspaces.</p>
                </div>
                <div className="flex gap-1 rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-background)] p-1">
                  {[
                    ["details", "Details"],
                    ["html", "HTML"],
                    ["css", "CSS"],
                    ["preview", "Preview"],
                  ].map(([tab, label]) => (
                    <Button
                      key={tab}
                      type="button"
                      variant={pdfWorkspaceTab === tab ? "secondary" : "ghost"}
                      size="sm"
                      aria-pressed={pdfWorkspaceTab === tab}
                      onClick={() => setPdfWorkspaceTab(tab as PdfWorkspaceTab)}
                    >
                      {label}
                    </Button>
                  ))}
                </div>
              </div>

              {pdfWorkspaceTab === "details" ? (
                <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]">
                  <label className="space-y-1 text-sm font-medium">
                    Template name
                    <Input value={pdfDraft.name} onChange={(event) => setPdfDraft({ ...pdfDraft, name: event.target.value })} />
                  </label>
                  <label className="space-y-1 text-sm font-medium">
                    Description
                    <Input
                      value={pdfDraft.description ?? ""}
                      onChange={(event) => setPdfDraft({ ...pdfDraft, description: event.target.value })}
                    />
                  </label>
                  <label className="mt-7 flex items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={pdfDraft.isDefault}
                      onChange={(event) => setPdfDraft({ ...pdfDraft, isDefault: event.target.checked })}
                    />
                    Default
                  </label>
                </div>
              ) : null}

              {pdfWorkspaceTab === "html" ? (
                <CodeEditorField
                  label="HTML template"
                  value={pdfDraft.htmlTemplate}
                  onChange={(htmlTemplate) => setPdfDraft({ ...pdfDraft, htmlTemplate })}
                  height="520px"
                  language="html"
                />
              ) : null}

              {pdfWorkspaceTab === "css" ? (
                <CodeEditorField
                  label="CSS"
                  value={pdfDraft.css}
                  onChange={(cssValue) => setPdfDraft({ ...pdfDraft, css: cssValue })}
                  height="520px"
                  language="css"
                />
              ) : null}

              <div className="flex flex-wrap gap-2">
                <Button type="button" onClick={savePdfTemplate} disabled={createPdfTemplate.isPending || updatePdfTemplate.isPending}>
                  <Save className="h-4 w-4" />
                  Save template
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    setPdfWorkspaceTab("preview");
                    previewCurrentPdfTemplate();
                  }}
                  disabled={previewPdfTemplate.isPending}
                >
                  <Eye className="h-4 w-4" />
                  Preview
                </Button>
              </div>

              {pdfMessage ? (
                <p className="rounded border border-[var(--color-border)] bg-[var(--color-background)] px-3 py-2 text-sm text-[var(--color-text-muted)]">
                  {pdfMessage}
                </p>
              ) : null}

              {pdfWorkspaceTab === "preview" ? (
                previewPdfTemplate.data?.html ? (
                  <iframe
                    title="PDF template preview"
                    srcDoc={previewPdfTemplate.data.html}
                    className="h-[520px] w-full rounded border border-[var(--color-border)] bg-white"
                  />
                ) : (
                  <div className="rounded border border-dashed border-[var(--color-border)] p-6 text-center text-sm text-[var(--color-text-muted)]">
                    Run preview to render the current HTML and CSS.
                  </div>
                )
              ) : null}
            </div>
          ) : (
            <div className="rounded border border-dashed border-[var(--color-border)] p-6 text-center text-sm text-[var(--color-text-muted)]">
              Select a PDF template or create one to edit branding.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
