import { execFile } from "node:child_process";
import { access, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import MarkdownIt from "markdown-it";
import sanitizeHtml from "sanitize-html";

const execFileAsync = promisify(execFile);

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  typographer: false
});

const allowedContentTags = [
  "a",
  "blockquote",
  "br",
  "code",
  "del",
  "em",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "li",
  "ol",
  "p",
  "pre",
  "strong",
  "table",
  "tbody",
  "td",
  "th",
  "thead",
  "tr",
  "ul"
];

const allowedTemplateTags = [
  ...allowedContentTags,
  "body",
  "div",
  "footer",
  "head",
  "html",
  "main",
  "meta",
  "section",
  "span",
  "style",
  "title"
];

const sanitizeOptions: sanitizeHtml.IOptions = {
  allowedTags: allowedTemplateTags,
  allowedAttributes: {
    "*": ["class", "id"],
    a: ["href", "title", "target", "rel"],
    meta: ["charset"],
    td: ["colspan", "rowspan"],
    th: ["colspan", "rowspan", "scope"]
  },
  allowedSchemes: ["http", "https", "mailto"],
  allowVulnerableTags: true,
  disallowedTagsMode: "discard",
  enforceHtmlBoundary: false,
  transformTags: {
    a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer" }, true)
  }
};

export const DEFAULT_PDF_CSS = `
@page {
  size: A4;
  margin: 22mm 18mm;
}

body {
  font-family: Arial, sans-serif;
  color: #17201d;
  font-size: 12px;
  line-height: 1.5;
}

.cover {
  page-break-after: always;
  padding-top: 90px;
}

.eyebrow {
  color: #0f766e;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-weight: 700;
}

h1 {
  font-size: 28px;
  line-height: 1.2;
  margin: 12px 0;
}

.meta {
  color: #66716d;
  margin-top: 20px;
  font-size: 12px;
}

.content h1 {
  font-size: 22px;
  border-bottom: 1px solid #d9dfdc;
  padding-bottom: 8px;
  margin-top: 0;
}

.content h2 {
  font-size: 16px;
  margin-top: 24px;
  border-bottom: 1px solid #e8ecea;
  padding-bottom: 4px;
}

.content h3 {
  font-size: 13px;
  margin-top: 18px;
}

.content p {
  margin: 8px 0;
}

.content ul,
.content ol {
  margin: 8px 0 12px 20px;
  padding: 0;
}

.content li {
  margin: 4px 0;
}

.content blockquote {
  border-left: 3px solid #d9dfdc;
  color: #66716d;
  margin: 12px 0;
  padding: 2px 0 2px 12px;
}

.content table {
  width: 100%;
  border-collapse: collapse;
  margin: 12px 0 18px;
  page-break-inside: auto;
  font-size: 11px;
}

.content thead {
  display: table-header-group;
}

.content tr {
  page-break-inside: avoid;
  page-break-after: auto;
}

.content th,
.content td {
  border: 1px solid #d9dfdc;
  padding: 6px 8px;
  vertical-align: top;
  overflow-wrap: anywhere;
  word-break: normal;
}

.content th {
  background: #f1f3f2;
  font-weight: 700;
  text-align: left;
  white-space: nowrap;
}

.content code {
  font-family: Consolas, monospace;
  background: #f1f3f2;
  padding: 1px 3px;
  border-radius: 3px;
}

.content pre {
  background: #f1f3f2;
  padding: 10px;
  overflow-wrap: break-word;
  white-space: pre-wrap;
  border-radius: 6px;
}

.content pre code {
  background: transparent;
  padding: 0;
}

.content a {
  color: #0f766e;
}

.footer {
  margin-top: 32px;
  padding-top: 12px;
  border-top: 1px solid #d9dfdc;
  color: #66716d;
  font-size: 10px;
}
`.trim();

export const DEFAULT_PDF_HTML_TEMPLATE = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>{{page.css}}</style>
</head>
<body>
  <section class="cover">
    <div class="eyebrow">DFIR Incident Report</div>
    <h1>{{report.title}}</h1>
    <div class="meta">
      <div>Incident: {{incident.name}}</div>
      <div>Client: {{incident.clientName}}</div>
      <div>Status: {{incident.status}}</div>
      <div>Generated: {{report.generatedAt}}</div>
    </div>
  </section>

  <main class="content">
    {{content}}
  </main>

  <section class="footer">
    Generated by Forenotes
  </section>
</body>
</html>`;

export function renderMarkdownToSanitizedHtml(markdownContent: string) {
  return sanitizeHtml(markdown.render(markdownContent || ""), sanitizeOptions);
}

export function renderPdfHtml(input: {
  report: { title: string; type: string; generatedAt: string; markdown: string };
  incident: { name: string; clientName: string; status: string };
  htmlTemplate: string;
  css: string;
}) {
  const replacements: Record<string, string> = {
    "report.title": escapeHtml(input.report.title || "Not provided"),
    "report.type": escapeHtml(input.report.type || "Not provided"),
    "report.generatedAt": escapeHtml(input.report.generatedAt || "Not provided"),
    "incident.name": escapeHtml(input.incident.name || "Not provided"),
    "incident.clientName": escapeHtml(input.incident.clientName || "Not provided"),
    "incident.status": escapeHtml(input.incident.status || "Not provided"),
    "page.css": sanitizeCss(input.css || DEFAULT_PDF_CSS),
    content: renderMarkdownToSanitizedHtml(input.report.markdown)
  };

  const rendered = input.htmlTemplate.replace(/{{\s*([^}]+?)\s*}}/g, (_match, rawKey: string) => {
    const key = rawKey.trim();
    return replacements[key] ?? "Not provided";
  });

  return sanitizeHtml(rendered, sanitizeOptions);
}

export async function renderHtmlToPdf(html: string) {
  const executable = await resolveChromiumExecutable();
  const workDir = await mkdtemp(path.join(tmpdir(), "forenotes-pdf-"));
  const htmlPath = path.join(workDir, "report.html");
  const pdfPath = path.join(workDir, "report.pdf");
  try {
    await writeFile(htmlPath, html, "utf8");
    await execFileAsync(
      executable,
      [
        "--headless=new",
        "--no-sandbox",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--run-all-compositor-stages-before-draw",
        "--no-pdf-header-footer",
        `--print-to-pdf=${pdfPath}`,
        pathToFileURL(htmlPath).href
      ],
      { timeout: 30_000, maxBuffer: 1024 * 1024 }
    );
    const pdf = await readFile(pdfPath);
    if (pdf.byteLength === 0) {
      throw new Error("Chromium produced an empty PDF.");
    }
    return pdf;
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

async function resolveChromiumExecutable() {
  const candidates = [
    process.env.PDF_CHROMIUM_EXECUTABLE_PATH,
    process.env.CHROME_PATH,
    ...(await agentBrowserChromeCandidates()),
    "/usr/bin/google-chrome-stable",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser"
  ];

  for (const candidate of candidates) {
    if (candidate && await pathExists(candidate)) {
      return candidate;
    }
  }

  for (const command of ["google-chrome-stable", "google-chrome", "chromium", "chromium-browser"]) {
    try {
      const { stdout } = await execFileAsync("which", [command]);
      const resolved = stdout.trim();
      if (resolved) {
        return resolved;
      }
    } catch {
      // Try the next executable name.
    }
  }

  throw new Error("Chromium executable not found for PDF export.");
}

async function agentBrowserChromeCandidates() {
  const root = path.join(homedir(), ".agent-browser", "browsers");
  try {
    const entries = await readdir(root, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isDirectory() && entry.name.startsWith("chrome-"))
      .map((entry) => path.join(root, entry.name, "chrome"))
      .sort()
      .reverse();
  } catch {
    return [];
  }
}

async function pathExists(filePath: string) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function sanitizeCss(value: string) {
  return value
    .replace(/<\/?style\b[^>]*>/gi, "")
    .replace(/expression\s*\([^)]*\)/gi, "")
    .replace(/url\s*\(\s*(['"]?)\s*(?:javascript|file):[^)]+\)/gi, "")
    .replace(/@import[^;]+;/gi, "");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
